### ISSUE TITLE
Add setting to disable automatic creation of semantic-build-versioning.gradle

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/hypertrace-gradle-version-settings-plugin#6]
Javaagent uses the version plugin but without deriving the version from git history.

The release version is created by the user explicitly (e.g. pushing a tag 0.2.0) see
https://github.com/hypertrace/javaagent/blob/main/RELEASE.md.

in the javaagent I use `./gradlew printVersion` task which creates the semantic-build-versioning.gradle. It would be good to disable the creating of this file if the end project is not using it.

**Comment by aaron-steinfeld** [comment]
So the plugin that does the heavy lifting requires it - https://github.com/vivin/gradle-semantic-build-versioning#usage 

> Additionally you need an (at least) empty semantic-build-versioning.gradle file in the corresponding project-directory of each project in the build that should be handled by this plugin.

I don’t think it’s worth the effort to move to a completely new impl or forking it, so I’d suggest either checking in an empty file or adding it to .gitignore.

**Comment by pavolloffay** [comment]
If it requires significant changes then it's fine to use the workaround. I have already added it to `.gitignore` and it works well.

**Comment by aaron-steinfeld** [comment]
Yep, this plugin is in reality just a configuration wrapper around that plugin - so this would require a full on implementation. Closing the issue unless you disagree.
